### ISSUE TITLE
Edge case handling towards v2 release

### ISSUE THREAD

**Issue by vijayiyer05** [schnitzer-lab/extract-wip#5]
This umbrella issue captures efforts to identify and handle remaining edge cases leading to error messages or avoidable warning messages today. Make code updates and/or add exception handling, seeking to avoid errors/warnings and/or provide more informative messages.  [Testing frameworks](https://www.mathworks.com/help/matlab/matlab-unit-test-framework.html) such as unit testing or mocking may be employed.

Specific tasks include:

- [x] Orientation to codebase with EXTRACT project leader
- [x] Exercising with the tutorial example datasets
- [x] Exercising (possibly formally testing) new NWB interoperability (#2), with DANDI datasets (should be motion corrected first)
- [x] Exercise with CNMF or other tool examples (again w/ motion correction)

**Comment by manisha-sinha-appasamy** [comment]
I have found 2 minor bugs while running the tutorials:

Minor bug1: In tutorial 1
```
Index in position 2 exceeds array bounds. Index must not exceed 19.

Error in example_tutorial (line 50)
plot(T_ex(idx_match(1,pick),:));
```

The value of 'pick' in tutorial 1 by default is 20 and leads to an error on running extract-wip. Of course, one can change the pick value to anything between 1-19 and the code works. 
NB: For tutorial 1, even though the ground truth is that there are 20 cells, extract-wip detects only 19. This result is different from extract-public, which correctly detects 20 cells. This difference might be worth looking into. Or it will probably go away once Fatih pushes updates for v1. 


Minor bug2: In extractor.m
```
29-Nov-2021 20:36:59: Signal extraction on partition 1 (of 1):
	 	 	 Discarding a [0 px top, 0 px bottom, 0 px left, 0 px right] inactive movie region. 
Undefined function 'nanstd' for input arguments of type 'single'.

Error in extractor (line 182)
    std_M = nanstd(M_small(:));

Error in tutorial_fig4 (line 23)
output=extractor(M,config);
```


To get rid of the error, please change line 182 in extractor.m to the following:
`std_M = std(M_small(:),'omitnan'); `

**Comment by Yambottle** [comment]
Hi Manisha,

Thanks for your update! I had your first issue as well, but I didn't get
the second one.
My local MATLAB was constantly crashing at the preprocessing stage when I'm
running Tutorial 3. There is no error or crash report either. My laptop
spec is:
- 3.1 GHz Dual-Core Intel Core i5
- 16 GB 2133 MHz LPDDR3
- macOS Big Sur ver11.1
- MATLAB R2021b

I did use the MATLAB Profiler to run through the Tutorial 2 dataset. Here
is the screenshot sorted by function Self Time:
[image: Screen Shot 2021-12-16 at 18.01.42.png]
Hope this helps to pinpoint the bottleneck!

--
Regards,
Drew Yang
Software Engineer, DataJoint
214.727.9608 <2147279608> | ***@***.***
https://calendly.com/drewyang

**Comment by Yambottle** [comment]
Hi Manisha,

Thanks for your update! I had your first issue as well, but I didn't get
the second one.
My local MATLAB was constantly crashing at the preprocessing stage when I'm
running Tutorial 3. There is no error or crash report either. My laptop
spec is:
- 3.1 GHz Dual-Core Intel Core i5
- 16 GB 2133 MHz LPDDR3
- macOS Big Sur ver11.1
- MATLAB R2021b

I did use the MATLAB Profiler to run through the Tutorial 2 dataset. Here
is the screenshot sorted by function Self Time:
![Screen Shot 2021-12-16 at 18 01 42](https://user-images.githubusercontent.com/31813282/146469367-6b520d9a-fd6e-4264-b53f-c3f6dfedc1c4.png)

Hope this helps to pinpoint the bottleneck!

**Comment by manisha-sinha-appasamy** [comment]
Hi Drew,

For tutorial 3, the issue is the large input file size (~11 GB). I had faced the same issue and found an alternative that works.

Comment out the following code that reads the entire HDF5 file:

`M = single(hdf5read('jones.hdf5','/Data/Images'));`

Now define the input filename as a string using the following format:

`M = 'jones.hdf5:/Data/Images';`

EXTRACT will accept this string as the first argument.

Then change the number of x and y partitions. For my Linux system (Ubuntu 20.04.3 LTS) with 24 GB RAM and NVIDIA Corporation GP107 [GeForce GTX 1050 Ti] GPU (which has 4 GB memory), the following configuration worked:

```
config.num_partitions_x=10;
config.num_partitions_y=10;
```
However, as far as I know, MATLAB supports only NVIDIA-based GPUs. So, if you are running it on your mac and if it does not have the supported GPU, it might still throw an error. It happened on my old MBP which has an Intel-based graphics card.

Could you please try out the following 2 commands on MATLAB on your mac and let me know what the output is:
```
gpuDeviceCount("available")
gpuDevice().DeviceSupported
```
Based on that, we may be able to resolve the edge-case of non-supported GPUs using the following code:
```
% If you do not have a native NVIDIA GPU, MATLAB may throw an error. 
if gpuDeviceCount("available")==0 || gpuDevice().DeviceSupported==0
   config.use_gpu=0;
end
```

Hope this helps! Please update us on how it goes.

Manisha

**Comment by vijayiyer05** [comment]
@Yambottle , @manisha-sinha-appasamy : great to see this discussion underway on edge cases and various install configurations of EXTRACT.

@Yambottle  - for the profiler screenshot you shared, I wonder if that's relevant for the performance issue #6? If so, perhaps can copy over to start that issue discussion.

**Comment by Yambottle** [comment]
Thanks @manisha-sinha-appasamy !  I'll try your suggestion. I got the 'GPU not available' error on my mac as well. Currently, I'm using CPU only to process.

Thanks @vijayiyer05 ! You are right about the screenshot, but that run was running with tutorial 2 example dataset. I'll see if I can make one using the tutorial 3 dataset.

**Comment by vijayiyer05** [comment]
@Yambottle, @manisha-sinha-appasamy  
Per my discussion w/ @fatihdinc: the latest & greatest from the public repository has been merged here into extract-wip. The algorithm code is now stable. 

It's encouraged now to submit code commits (changes) based upon your use case assessment. These may also become suggestions (pull requests) for the public repository to help improve its quality.
